spring:
  application:
    name: muthub-id
  profiles:
    active: consul
  autoconfigure:
    exclude: org.springframework.cloud.zookeeper.serviceregistry.ZookeeperAutoServiceRegistrationAutoConfiguration
  cloud:
    zookeeper:
        connect-string: 123.57.59.153:2181
        discovery:
            register: false
    consul:
      host: 123.57.59.153
      port: 8500
      discovery:
        service-name: muthub-id
        heartbeat:
          enabled: true
server:
  port: 10001
logging:
  level:
    root: info
  file:
    name: ./log/muthub-id.log
dubbo:
  application:
    name: muthub-id
  protocol:
    name: dubbo
    port: -1
  registry:
    address: consul://123.57.59.153:8500
