spring:
  application:
    name: muthub-gateway
  profiles:
    active: consul
  cloud:
    consul:
      host: 123.57.59.153
      port: 8500
      discovery:
        service-name: muthub-gateway
        heartbeat:
          enabled: true
    gateway:
      routes:
        - id: user-service
          uri: lb://muthub-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host:  120.46.208.70
    password:
  server:
    port: 10240
  logging:
    level:
      root: info
    file:
      name: ./log/muthub-gateway.log
secure:
  ignore:
    urls:
      - "/register"
      - "/user/login"
